language: node_js
node_js:
  - node
  - '12'
  - '10'
  - '8'
install:
  - yarn install
script:
  - yarn run ci-test
deploy:
  provider: npm
  email: jonathan.griggs@gmail.com
  api_key:
    secure: D8JNpgSSWmDtbw18zkZJeUClzRGUChJ/OIw5zrVcNspNnw8ttQ/fA8FvY7DpG06YrVq/MaMjN5tRevjky1XzES9MxKptVzkkttL55YFdprVOeAc3p4C095HOgW0vAUfYblNpSix4ldmzzoXmFiooszJRpUVWkX4pY0xpkfubXAsrTOVmUiiDZfN5xJSCtDP/P5socUwh3uWbDNJxw2txaX+M9TuGzGLQKYqvK/6azMhZNzFu4FP1DfDntJjC+L9xvTMm9o1yDTkVkHDChQWbHronDUD5YQQYRtE+9QerHV3yA7O0wipOWiJT8EknFw5JNM0nNFUBVBBW8yXFC5YtjgAbbH4SmWLZOADUt6pMvjyskYc3YBKS64Kfk7fCJCV6CPZToHymMaoNHXADhzpHqtfKVjFvHXeYHksshJ8T99WUwS9r/TfzH2h3MjncND4wYM/iW4BO0iN56/cmDpnTpjRg/Jzuv2K2LH4hOtkmX63Yfar+jAt4SrrjewoyzqJVnrIrAaMB6jaqGzAtE4Jazz/l7FZdjGX7AADruCyy4q/3RHsE0sY1vjiPRuV8mR9zrP04IMHOhmelgB+vdTt1fnwTu0EdpiLaovYwRYEXAg5nsleHiPMkY5Sj93g+CKxD4etKvJc7WZgRF8aFEPXqZSF/PDyIZC3ZYUgLyMkm52M=
  on:
    tags: true
    repo: growombud/omnesiac
    branch: master
